---
include:
  - 'https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/PreCommit.gitlab-ci.yml'
  - remote: 'https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/SonarScanner.gitlab-ci.yml'

.runner_tags: &runner_tags
  tags:
    - docker

stages:
    - check
    - testpy37
    - testpy38
    - analyse

test 1/2:
  <<: *runner_tags
  stage: testpy38
  image: python:3.8
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -e py38
  artifacts:
    paths:
      - unittest.xml
      - coverage.xml
    expire_in: 24 hour

test 2/2:
  <<: *runner_tags
  stage: testpy37
  image: python:3.7
  before_script:
    - python -m pip install --upgrade pip
    - pip install tox
  script:
    - tox -e py37
  artifacts:
    paths:
      - unittest.xml
      - coverage.xml
    expire_in: 24 hour
